ORANGE = 0xFF751A
YELLOW = 0xFFFF1A
GREEN = 0x66FF33
RED = 0xFF1A1A

COLOR_STARTED = 0x004D00
COLOR_ENDED = 0x00FF00

COLOR_DUAL_STARTED = 0x00004D
COLOR_DUAL_ENDED = 0x0000FF

COLOR_CHAT_STARTED = 0x006666
COLOR_CHAT_ENDED = 0x00FFFF

COLOR_ADMIN_CMD = 0x660066, 0xE600E6

t5_t7 = [
    "VII FLORIDA",
    "VII CALIFORNIA",
    "VII HOOD",
    "VII DUKE OF YORK",
    "VII STRASBOURG",
    "VII SCHARNHORST",
    "VII ASHITAKA",
    "VII HYŪGA",
    "VII POLTAVA",
    "VII ATLANTA",
    "VII INDIANAPOLIS",
    "VII BOISE",
    "VII MÜNCHEN",
    "VII WEIMAR",
    "VII DUCA DEGLI ABRUZZI",
    "VII GORIZIA",
    "VII LAZO",
    "VII NUEVE DE JULIO",
    "VII YUKON",
    "VII SIMS",
    "VII YŪDACHI",
    "VII LENINGRAD",
    "VII BŁYSKAWICA",
    "VI ARK ROYAL",
    "VI W. VIRGINIA 1941",
    "VI ARIZONA",
    "VI WARSPITE",
    "VI DUNKERQUE",
    "VI PRINZ EITEL FRIEDRICH",
    "VI MUTSU",
    "VI LONDON",
    "VI DE GRASSE",
    "VI DUCA D'AOSTA",
    "VI MOLOTOV",
    "VI ADMIRAL MAKAROV",
    "VI PERTH",
    "VI MYSORE",
    "VI HUANGHE",
    "VI ISE",
    "VI MONAGHAN",
    "VI GALLANT",
    "VI AIGLE",
    "VI LEONE",
    "VI JURUÁ",
    "VI ANSHAN",
    "V TEXAS",
    "V AGINCOURT",
    "V OKTYABRSKAYA REVOLUTSIYA",
    "V VIRIBUS UNITIS",
    "V MARBLEHEAD",
    "V MARBLEHEAD LIMA",
    "V EXETER",
    "V GENOVA",
    "V YAHAGI",
    "V MURMANSK",
    "V KRASNY KRYM",
    "V MIKOYAN",
    "V KIROV",
    "V HILL",
    "V SIROCO",
    "V OKHOTNIK",
]

t8_t9 = [
    "IX POMMERN",
    "IX MARCO POLO",
    "IX ÄGIR",
    "IX AZUMA",
    "IX Z-44",
    "IX GRONINGEN",
    "VIII SAIPAN",
    "VIII INDOMITABLE",
    "VIII GRAF ZEPPELIN",
    "VIII KAGA",
    "VIII ALABAMA",
    "VIII CONSTELLATION",
    "VIII VANGUARD",
    "VIII GASCOGNE",
    "VIII CHAMPAGNE",
    "VIII FLANDRE",
    "VIII TIRPITZ",
    "VIII ROMA",
    "VIII KII",
    "VIII BORODINO",
    "VIII CONGRESS",
    "VIII WICHITA",
    "VIII CHESHIRE",
    "VIII TIGER '59",
    "VIII BELFAST '43",
    "VIII BAYARD",
    "VIII PRINZ EUGEN",
    "VIII MAINZ",
    "VIII ATAGO",
    "VIII TONE",
    "VIII OCHAKOV",
    "VIII PYOTR BAGRATION",
    "VIII IRIAN",
    "VIII KIDD",
    "VIII COSSACK",
    "VIII LE TERRIBLE",
    "VIII Z-35",
    "VIII ORKAN",
    "VIII LOYANG",
    "VIII FENYANG",
    "VIII SILIWANGI",
]

t10_rare = [
    "X MAX IMMELMANN",
    "X THUNDERER",
    "X MARCEAU",
    "X HAYATE",
    "X SMÅLAND",
    "X SALEM",
    "X NAPOLI",
    "X YOSHINO",
    "X MOSKVA",
    "X SMOLENSK",
    "IX MISSOURI",
    "IX GEORGIA",
    "IX JEAN BART",
    "IX MUSASHI",
    "IX BENHAM",
    "IX NEUSTRASHIMY",
    "IX FRIESLAND",
    "IX ALASKA",
    "IX KRONSHTADT",
    "VIII ENTERPRISE",
    "VIII MASSACHUSETTS",
    "VIII LENIN",
    "VIII ASASHIO",
    "VIII MIKHAIL KUTUZOV",
    "VII Z-39",
    "VII HAIDA",
    "VII NELSON",
    "VII FLINT",
    "VII BELFAST",
    "VI ERICH LOEWENHARDT",
    "VI ADMIRAL GRAF SPEE",
    "VI T-61",
]

BOX_MEGA = [
    {
        "chance": 0.40,
        "type": "multi",
        "value": [
            {"chance": 0.125, "name": "30x Dragon"},
            {"chance": 0.125, "name": "30x Red Dragon"},
            {"chance": 0.125, "name": "30x Wyvern"},
            {"chance": 0.125, "name": "30x Hydra"},
            {"chance": 0.125, "name": "30x Ouroboros"},
            {"chance": 0.125, "name": "30x Basilisk"},
            {"chance": 0.125, "name": "30x Scylla"},
            {"chance": 0.125, "name": "30x Leviathan"},
        ],
    },
    {
        "chance": 0.09,
        "type": "multi",
        "value": [
            {"chance": 0.333, "name": "20x Winter Strands"},
            {"chance": 0.333, "name": "20x Frosty Fir Tree"},
            {"chance": 0.333, "name": "20x New Year Streamer"},
        ],
    },
    {"chance": 0.1, "type": "single", "value": "20x New Year Sky camouflages"},
    {"chance": 0.06, "type": "single", "value": "25x Type 3 - New Year"},
    {
        "chance": 0.06,
        "type": "multi",
        "value": [
            {"chance": 0.333, "name": "5x Spring Sky"},
            {"chance": 0.333, "name": "5x Asian Lantern"},
            {"chance": 0.333, "name": "5x Mosaic"},
        ],
    },
    {"chance": 0.01, "type": "single", "value": "180 days of Warships Premium Account"},
    {"chance": 0.07, "type": "single", "value": "12,500 Coal"},
    {"chance": 0.05, "type": "single", "value": "2,500 Doubloons"},
    {
        "chance": 0.16,
        "type": "multi",
        "value": [
            {"chance": 0.12, "name": t5_t7},
            {"chance": 0.03, "name": t8_t9},
            {"chance": 0.01, "name": t10_rare},
        ],
    },
]
BOX_BIG = [
    {
        "chance": 0.32,
        "type": "multi",
        "value": [
            {"chance": 0.125, "name": "15x Dragon"},
            {"chance": 0.125, "name": "15x Red Dragon"},
            {"chance": 0.125, "name": "15x Wyvern"},
            {"chance": 0.125, "name": "15x Hydra"},
            {"chance": 0.125, "name": "15x Ouroboros"},
            {"chance": 0.125, "name": "15x Basilisk"},
            {"chance": 0.125, "name": "15x Scylla"},
            {"chance": 0.125, "name": "15x Leviathan"},
        ],
    },
    {
        "chance": 0.18,
        "type": "multi",
        "value": [
            {"chance": 0.333, "name": "12x Winter Strands"},
            {"chance": 0.333, "name": "12x Frosty Fir Tree"},
            {"chance": 0.333, "name": "12x New Year Streamer"},
        ],
    },
    {"chance": 0.16, "type": "single", "value": "12x New Year Sky camouflages"},
    {"chance": 0.12, "type": "single", "value": "15x Type 3 - New Year"},
    {"chance": 0.01, "type": "single", "value": "90 days of Warships Premium Account"},
    {"chance": 0.07, "type": "single", "value": "7,500 Coal"},
    {"chance": 0.05, "type": "single", "value": "1,500 Doubloons"},
    {
        "chance": 0.09,
        "type": "multi",
        "value": [
            {"chance": 0.07, "name": t5_t7},
            {"chance": 0.015, "name": t8_t9},
            {"chance": 0.005, "name": t10_rare},
        ],
    },
]
BOX_NORM = [
    {
        "chance": 0.40,
        "type": "multi",
        "value": [
            {"chance": 0.25, "name": "50x Zulu"},
            {"chance": 0.25, "name": "50x Papa Papa"},
            {"chance": 0.25, "name": "50x Zulu Hotel"},
            {"chance": 0.25, "name": "50x Equal Speed Charlie London"},
        ],
    },
    {
        "chance": 0.08,
        "type": "multi",
        "value": [
            {"chance": 0.125, "name": "5x Dragon"},
            {"chance": 0.125, "name": "5x Red Dragon"},
            {"chance": 0.125, "name": "5x Wyvern"},
            {"chance": 0.125, "name": "5x Hydra"},
            {"chance": 0.125, "name": "5x Ouroboros"},
            {"chance": 0.125, "name": "5x Basilisk"},
            {"chance": 0.125, "name": "5x Scylla"},
            {"chance": 0.125, "name": "5x Leviathan"},
        ],
    },
    {
        "chance": 0.15,
        "type": "multi",
        "value": [
            {"chance": 0.333, "name": "4x Winter Strands"},
            {"chance": 0.333, "name": "4x Frosty Fir Tree"},
            {"chance": 0.333, "name": "4x New Year Streamer"},
        ],
    },
    {"chance": 0.115, "type": "single", "value": "4x New Year Sky camouflages"},
    {"chance": 0.10, "type": "single", "value": "5x Type 3 - New Year"},
    {"chance": 0.01, "type": "single", "value": "30 days of Warships Premium Account"},
    {"chance": 0.07, "type": "single", "value": "2,500 Coal"},
    {"chance": 0.05, "type": "single", "value": "500 Doubloons"},
    {
        "chance": 0.025,
        "type": "multi",
        "value": [
            {"chance": 0.02, "name": t5_t7},
            {"chance": 0.004, "name": t8_t9},
            {"chance": 0.001, "name": t10_rare},
        ],
    },
]
